version: '3.8'
services:
    db1:
        image: postgres:latest
        container_name: url_shortener_db
        environment:
            POSTGRES_USER: alexnov
            POSTGRES_PASSWORD: alexnov
            POSTGRES_DB: db
        ports: 
            - "5432:5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
    mainservice:
        build: .
        container_name: url_shortener
        ports:
            - "8080:8080"
        command: ["./output", "-in-memory=true"]
        depends_on:
            - db1