// Code generated by MockGen. DO NOT EDIT.
// Source: urldelivery.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUrlUsecase is a mock of UrlUsecase interface.
type MockUrlUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUrlUsecaseMockRecorder
}

// MockUrlUsecaseMockRecorder is the mock recorder for MockUrlUsecase.
type MockUrlUsecaseMockRecorder struct {
	mock *MockUrlUsecase
}

// NewMockUrlUsecase creates a new mock instance.
func NewMockUrlUsecase(ctrl *gomock.Controller) *MockUrlUsecase {
	mock := &MockUrlUsecase{ctrl: ctrl}
	mock.recorder = &MockUrlUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlUsecase) EXPECT() *MockUrlUsecaseMockRecorder {
	return m.recorder
}

// GetOriginalUrl mocks base method.
func (m *MockUrlUsecase) GetOriginalUrl(ctx context.Context, shortUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalUrl", ctx, shortUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalUrl indicates an expected call of GetOriginalUrl.
func (mr *MockUrlUsecaseMockRecorder) GetOriginalUrl(ctx, shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalUrl", reflect.TypeOf((*MockUrlUsecase)(nil).GetOriginalUrl), ctx, shortUrl)
}

// ShortenUrl mocks base method.
func (m *MockUrlUsecase) ShortenUrl(ctx context.Context, originalUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortenUrl", ctx, originalUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortenUrl indicates an expected call of ShortenUrl.
func (mr *MockUrlUsecaseMockRecorder) ShortenUrl(ctx, originalUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortenUrl", reflect.TypeOf((*MockUrlUsecase)(nil).ShortenUrl), ctx, originalUrl)
}
